# 가장 중요!!!

- list: 불연속(Linked List구조), 속도가 느림<br>[1, 2, 3]: 콤마로 구분. 서로 다른 자료형 사용 가능
- ArrayList(ndArray): 연속된 메모리 구조. 속도가 빠름<br> 콤마로 구분하지 않고 공백으로 요소를 구분<br> 동일한 자료형만 갖을 수 있음


In [1]:
import numpy as np

In [2]:
# list
list1 = [1, 2, 3, 4, 5, "python"]
print(list1, ":", type(list1))

[1, 2, 3, 4, 5, 'python'] : <class 'list'>


In [4]:
# ndarray
a = np.array([1,2,3,4,5], dtype="int32")
print(a, type(a))
print(a.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'>
int32


In [5]:
b = np.array([1, 2, "a"])
b

array(['1', '2', 'a'], dtype='<U21')

In [7]:
np.sctypeDict.keys()

dict_keys(['bool', 'float16', 'float32', 'float64', 'longdouble', 'complex64', 'complex128', 'clongdouble', 'bytes_', 'str_', 'void', 'object_', 'datetime64', 'timedelta64', 'int8', 'byte', 'uint8', 'ubyte', 'int16', 'short', 'uint16', 'ushort', 'int32', 'intc', 'uint32', 'uintc', 'int64', 'long', 'uint64', 'ulong', 'longlong', 'ulonglong', 'intp', 'uintp', 'double', 'cdouble', 'single', 'csingle', 'half', 'bool_', 'int_', 'uint', 'float', 'complex', 'object', 'bytes', 'a', 'int', 'str', 'unicode', 'float128', 'complex256'])

In [11]:
a = np.arange(10)
print(a, ";", type(a))
print(a.dtype)
print(a.shape)
print(a.ndim)

[0 1 2 3 4 5 6 7 8 9] ; <class 'numpy.ndarray'>
int64
(10,)
1


In [12]:
list2 = [[0, 1, 2],
         [3, 4, 5]]
list2

[[0, 1, 2], [3, 4, 5]]

In [17]:
m = np.array( [[0, 1, 2],
         [3, 4, 5]])
print(m, ":", type(m))
print(m.shape)
print(m.shape[1])
print(m.ndim)

[[0 1 2]
 [3 4 5]] : <class 'numpy.ndarray'>
(2, 3)
3
2


In [22]:
# 3차원 배열(면, 행, 열)

m2 = np.array([[[0, 1, 2], [3, 4, 5]],
               [[6, 7, 8], [9, 10, 11]]])
print(m2, ": ", m2.shape, m2.ndim)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] :  (2, 2, 3) 3


In [24]:
m3 = np.array([[[0, 1], [2, 3]],
              [[2, 3], [4, 5]]])
print(m3.ndim, m3.shape)

3 (2, 2, 2)


In [25]:
m1 = np.arange(12)
print(m1, m1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [26]:
m2 = m1.reshape(3, 4)
print(m2, m2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [27]:
m2 = m1.reshape(2, 6)
print(m2, m2.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [28]:
m3 = m1.reshape(2, 2, 3)
print(m3, m3.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [29]:
m4 = m1.reshape(1, 2, 2, -1, 1, 1)
print(m4, m4.shape)

[[[[[[ 0]]

    [[ 1]]

    [[ 2]]]


   [[[ 3]]

    [[ 4]]

    [[ 5]]]]



  [[[[ 6]]

    [[ 7]]

    [[ 8]]]


   [[[ 9]]

    [[10]]

    [[11]]]]]] (1, 2, 2, 3, 1, 1)


In [30]:
d = np.arange(12)

# indexing
print(d[0], d[1], d[-1])

0 1 11


In [34]:
# 슬라이싱
print(d[2:8])
print(d[:])
print(d[:-1])
print(d[::2])
print(d[::-1])

[2 3 4 5 6 7]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]
[11 10  9  8  7  6  5  4  3  2  1  0]


In [35]:
# 2차원
d = np.arange(12)
print(d, d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [36]:

d = np.arange(12).reshape(3, 4)
print(d, d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [39]:
print(d[0, :])
print(d[:,:]) # d[:, ]
print(d[:, :-1])

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [41]:
print(d[::2, ::2])

[[ 0  2]
 [ 8 10]]


In [42]:
d[::2, ::3] = 100
d

array([[100,   1,   2, 100],
       [  4,   5,   6,   7],
       [100,   9,  10, 100]])

In [37]:
print(d[2])
print(d[0][0], d[0,0])
print(d[1, 3])

[ 8  9 10 11]
0 0
7


In [43]:
d = np.arange(12).reshape(2, 2, 3) # 면, 행,열
print(d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [45]:
print(d[0])
print(d[0][0])
print(d[0][0][0])

[[0 1 2]
 [3 4 5]]
[0 1 2]
0


In [50]:
print(d[0, 1, 2])

5
