In [1]:
import tensorflow as tf

In [ ]:
scalar = tf.constant([1,2,3])
print(scalar)
print(scalar.shape, scalar.dtype)
print(tf.rank())

tf.Tensor(1, shape=(), dtype=int32)
() <dtype: 'int32'>


In [3]:
metrix = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
print(metrix)
print(tf.rank(metrix))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [4]:
tensor = tf.constant([[[1,2,3], [4,5,6], [7,8,9]],
                      [[1,2,3], [4,5,6], [7,8,9]],
                      [[1,2,3], [4,5,6], [7,8,9]]])
print(tensor) # shap = (면, 행, 열)
print(tf.rank(tensor))

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(3, 3, 3), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [5]:
print(metrix.shape, metrix.dtype)
print(tensor.shape, tensor.dtype)

(3, 3) <dtype: 'int32'>
(3, 3, 3) <dtype: 'int32'>


In [6]:
import numpy as np
a = np.zeros(10)
print(a.dtype)

float64


In [7]:
from tensorflow import keras

In [8]:
X = np.array([-1.0, 0.0, 1.0, 2.0,3.0,4.0], dtype=np.float32)
X

array([-1.,  0.,  1.,  2.,  3.,  4.], dtype=float32)

In [9]:
y = np.array([-3.0, -1.0, 1.0, 3.0,4.0,7.0], dtype=np.float32)
y

array([-3., -1.,  1.,  3.,  4.,  7.], dtype=float32)

In [10]:
# 모델 생성
model = keras.Sequential([keras.layers.Dense(1, input_shape=[1])])
model

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<Sequential name=sequential, built=True>

In [11]:
model.compile(loss='mean_squared_error', optimizer='sgd')
model.fit(X, y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 712ms/step - loss: 26.3803
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - loss: 21.0895
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 16.9206
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 13.6345
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 11.0430
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 8.9982
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 7.3836
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 6.1075
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 5.0980
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 4.2982
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 3.6636
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 3.1591
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 2.7570
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 2.4355
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 2.1777
Epoc