In [15]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [5]:
# 1. 데이터 준비
data_set = np.loadtxt("ThoraricSurgery3.csv", delimiter=",")
print(type(data_set))
print(data_set.shape)
print(data_set.dtype)

<class 'numpy.ndarray'>
(470, 17)
float64


In [9]:
X = data_set[:, :-1]
X # train data

array([[ 1.  ,  2.88,  2.16, ...,  1.  ,  0.  , 60.  ],
       [ 2.  ,  3.4 ,  1.88, ...,  1.  ,  0.  , 51.  ],
       [ 2.  ,  2.76,  2.08, ...,  1.  ,  0.  , 59.  ],
       ...,
       [ 2.  ,  3.04,  2.08, ...,  0.  ,  0.  , 52.  ],
       [ 2.  ,  1.96,  1.68, ...,  1.  ,  0.  , 79.  ],
       [ 2.  ,  4.72,  3.56, ...,  1.  ,  0.  , 51.  ]])

In [13]:
y = data_set[:, 16]
y # label, target

array([0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0.

In [14]:
print(X.shape)
print(y.shape)

(470, 16)
(470,)


In [17]:
#2.모델의 표현방법(NN)
model = Sequential()
model.add(Dense(30, input_dim=16, activation ='relu', name='layer1' ))  # input_dim은 은닉층에만 있

dense = Dense(1, activation='sigmoid', name='layer2')
model.add(dense)
#model.summary()

dense.get_weights()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


[array([[-0.34809867],
        [-0.1547057 ],
        [-0.17574793],
        [-0.1302005 ],
        [-0.28660804],
        [-0.34766892],
        [ 0.35282153],
        [ 0.31423098],
        [ 0.24911934],
        [ 0.09626484],
        [-0.14687303],
        [-0.05948994],
        [-0.10819823],
        [ 0.19615233],
        [ 0.04424259],
        [-0.351103  ],
        [-0.25296304],
        [-0.00269422],
        [-0.38200295],
        [ 0.09230757],
        [-0.2560229 ],
        [ 0.19375932],
        [ 0.3776865 ],
        [-0.21595255],
        [ 0.12521589],
        [ 0.43911344],
        [-0.31854835],
        [-0.2826817 ],
        [-0.22079448],
        [ 0.21566218]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
# 모델의 환경 설정
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# 기계학습
hist = model.fit(X, y, epochs=100, batch_size=10)

Epoch 1/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8330 - loss: 0.4081
Epoch 2/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8558 - loss: 0.3968
Epoch 3/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8631 - loss: 0.3724
Epoch 4/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8389 - loss: 0.4055
Epoch 5/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8541 - loss: 0.3765
Epoch 6/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8507 - loss: 0.3904
Epoch 7/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8581 - loss: 0.3628
Epoch 8/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8435 - loss: 0.3908
Epoch 9/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8696 - loss: 0.3376
Epoch 10/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8655 - loss: 0.3695
Epoch 11/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8491 - loss: 0.3730
Epoch 12/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy:

In [22]:
hist

In [25]:
print(type(hist))
hist.history

<class 'keras.src.callbacks.history.History'>


{'accuracy': [0.8468084931373596,
  0.8510638475418091,
  0.8553191423416138,
  0.8553191423416138,
  0.8531914949417114,
  0.8531914949417114,
  0.8510638475418091,
  0.8531914949417114,
  0.8553191423416138,
  0.8446808457374573,
  0.8531914949417114,
  0.848936140537262,
  0.8510638475418091,
  0.8574467897415161,
  0.8574467897415161,
  0.8468084931373596,
  0.8446808457374573,
  0.8574467897415161,
  0.8468084931373596,
  0.8510638475418091,
  0.848936140537262,
  0.8361701965332031,
  0.8468084931373596,
  0.8553191423416138,
  0.848936140537262,
  0.848936140537262,
  0.8510638475418091,
  0.8510638475418091,
  0.8574467897415161,
  0.8531914949417114,
  0.848936140537262,
  0.8595744967460632,
  0.8510638475418091,
  0.8531914949417114,
  0.8510638475418091,
  0.8553191423416138,
  0.8510638475418091,
  0.8468084931373596,
  0.8595744967460632,
  0.848936140537262,
  0.8595744967460632,
  0.8510638475418091,
  0.8553191423416138,
  0.8468084931373596,
  0.8468084931373596,
  0.

In [28]:
print(len(hist.history['loss']))
print(hist.history['loss'])
print(hist.history['accuracy'])

100
[0.3824700117111206, 0.3850855827331543, 0.37936219573020935, 0.37817662954330444, 0.3793773651123047, 0.3930913805961609, 0.38713058829307556, 0.3967147767543793, 0.37323710322380066, 0.3798675537109375, 0.3725091814994812, 0.3844248950481415, 0.3796669542789459, 0.37809187173843384, 0.3750516474246979, 0.37537023425102234, 0.38095980882644653, 0.3764318525791168, 0.381626695394516, 0.37656375765800476, 0.3935999870300293, 0.39784878492355347, 0.3866068124771118, 0.38910895586013794, 0.37306350469589233, 0.3793048560619354, 0.37276491522789, 0.3802720308303833, 0.37970301508903503, 0.3722662627696991, 0.37427979707717896, 0.3787570297718048, 0.37849557399749756, 0.38342583179473877, 0.39073529839515686, 0.374836266040802, 0.3825886845588684, 0.3838053047657013, 0.3717740774154663, 0.399850070476532, 0.36941128969192505, 0.3708975315093994, 0.3710983097553253, 0.37051039934158325, 0.3691509962081909, 0.3808756470680237, 0.378187358379364, 0.3733152151107788, 0.38184720277786255, 0.