In [1]:
import pandas as pd

In [2]:
obj = pd.Series([3,22,34,11], dtype='int32')
print(obj)

0     3
1    22
2    34
3    11
dtype: int32


In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([ 3, 22, 34, 11], dtype=int32)

In [5]:
type(obj.values)

numpy.ndarray

In [6]:
print(obj.dtype)
print(obj.shape)
print(obj.ndim)

int32
(4,)
1


In [7]:
obj2 = pd.Series([4,5,6,2], index=['c','d','e','f'])
print(obj2)
print(obj2['c'])
print(obj2[['c','f','d']])
print(obj2 * 2)

c    4
d    5
e    6
f    2
dtype: int64
4
c    4
f    2
d    5
dtype: int64
c     8
d    10
e    12
f     4
dtype: int64


In [8]:
'c' in obj2

True

In [9]:
'b' in obj2

False

In [10]:
data = {'kim':3000,'hong':2000,'kang':1000,'lee':1000}
obj3 = pd.Series(data)
print(obj3)

kim     3000
hong    2000
kang    1000
lee     1000
dtype: int64


In [12]:
name = ['woo','hong','kang','lee']

obj4 = pd.Series(data, index=name)
print(obj4)

woo        NaN
hong    2000.0
kang    1000.0
lee     1000.0
dtype: float64


In [13]:
print(pd.isnull(obj4))

woo      True
hong    False
kang    False
lee     False
dtype: bool


In [14]:
print(pd.notnull(obj4))

woo     False
hong     True
kang     True
lee      True
dtype: bool


In [15]:
data = {'seoul':4000,'busan':2000,'incheon':1500,'daegu':1000}
print(data)

obj = pd.Series(data)
print(obj)

{'seoul': 4000, 'busan': 2000, 'incheon': 1500, 'daegu': 1000}
seoul      4000
busan      2000
incheon    1500
daegu      1000
dtype: int64


In [16]:
cities = ['seoul','kimhae','incheon','daegu']
obj2 = pd.Series(data, cities)

print(obj2)

seoul      4000.0
kimhae        NaN
incheon    1500.0
daegu      1000.0
dtype: float64


In [17]:
print(obj + obj2)

busan         NaN
daegu      2000.0
incheon    3000.0
kimhae        NaN
seoul      8000.0
dtype: float64


In [18]:
obj2.name = '인구수'
print(obj2)

seoul      4000.0
kimhae        NaN
incheon    1500.0
daegu      1000.0
Name: 인구수, dtype: float64


In [19]:
obj2.index.name = '도시'
print(obj2)

도시
seoul      4000.0
kimhae        NaN
incheon    1500.0
daegu      1000.0
Name: 인구수, dtype: float64


In [20]:
#DataFrame
a = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [21]:
print(a)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [22]:
print(a.index)
print(a.columns)
print(a.values)
print(a.ndim)

RangeIndex(start=0, stop=3, step=1)
RangeIndex(start=0, stop=3, step=1)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [23]:
data = {'city': ['서울','부산','광주','대구'],
        'year': [2000,2001,2002,2001],
        'pop' : [4000,2000,1000,1000]}


In [24]:
df = pd.DataFrame(data)
df

city  year   pop
0   서울  2000  4000
1   부산  2001  2000
2   광주  2002  1000
3   대구  2001  1000

In [25]:
df2 = pd.DataFrame(data, columns=['year','city','pop'] )
df2

year city   pop
0  2000   서울  4000
1  2001   부산  2000
2  2002   광주  1000
3  2001   대구  1000

In [26]:
df3 = pd.DataFrame(data, columns=['year','city','pop','debt'],
                   index=['one','two','three','four'])
df3

year city   pop debt
one    2000   서울  4000  NaN
two    2001   부산  2000  NaN
three  2002   광주  1000  NaN
four   2001   대구  1000  NaN

In [27]:
print(df3['city'])
print(type(df3['city']))

one      서울
two      부산
three    광주
four     대구
Name: city, dtype: object
<class 'pandas.core.series.Series'>


In [28]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, one to four
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   year    4 non-null      int64 
 1   city    4 non-null      object
 2   pop     4 non-null      int64 
 3   debt    0 non-null      object
dtypes: int64(2), object(2)
memory usage: 332.0+ bytes


In [29]:
print(df3.dtypes)

year     int64
city    object
pop      int64
debt    object
dtype: object


In [30]:
df3['debt'] = 1000
df3

year city   pop  debt
one    2000   서울  4000  1000
two    2001   부산  2000  1000
three  2002   광주  1000  1000
four   2001   대구  1000  1000

In [31]:
df3['debt'] = range(4)
df3

year city   pop  debt
one    2000   서울  4000     0
two    2001   부산  2000     1
three  2002   광주  1000     2
four   2001   대구  1000     3

In [32]:
val = pd.Series([1000,2000,5000,3000], index=['one','two','three','four'])
val

one      1000
two      2000
three    5000
four     3000
dtype: int64

In [33]:
df3['debt'] = val
df3

year city   pop  debt
one    2000   서울  4000  1000
two    2001   부산  2000  2000
three  2002   광주  1000  5000
four   2001   대구  1000  3000

In [34]:
df3.city

one      서울
two      부산
three    광주
four     대구
Name: city, dtype: object

In [35]:
df3['aaa'] = df3.city == '서울'
df3

year city   pop  debt    aaa
one    2000   서울  4000  1000   True
two    2001   부산  2000  2000  False
three  2002   광주  1000  5000  False
four   2001   대구  1000  3000  False

In [36]:
del df3['aaa']

In [37]:
df3

year city   pop  debt
one    2000   서울  4000  1000
two    2001   부산  2000  2000
three  2002   광주  1000  5000
four   2001   대구  1000  3000